### ISSUE TITLE
Ragdoll prediction issues

### ISSUE THREAD

**Issue by eyal282** [bycop/fivem-ragdoll#1]
Every single script with the ragdoll I find ( this is exactly the same script ) causes the ragdoll to appear to its player in a different place than everybody else's. This means the ragdoll is sometimes unshootable, as the coords differ.

**Comment by bycop** [comment]
The difference in ragdoll position from player to player is due to the desynchronization of FiveM most of the time when an undefined behavior/animation is called.

**Comment by eyal282** [comment]
> The difference in ragdoll position from player to player is due to the desynchronization of FiveM most of the time when an undefined behavior/animation is called.

So that's exclusive to my server? Why only when ragdolling?

**Comment by bycop** [comment]
It's not only on your server, it happens on many others. Why only the ragdoll? Because it's an animation without defined behavior (for example a dance is immobile so it doesn't move indefinitely). But the ragdoll can be moved according to the interactions which can lead to desync
